// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfxdnaamehrrnhuuswmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeGRuYWFtZWhycm5odXVzd21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTQxMjAsImV4cCI6MjA2ODMzMDEyMH0.UbnH1_qc6B-q8FrKWTfmgju4jxop6jA0LyvuWMiQ0XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});